# https://docs.zephyrproject.org/latest/develop/west/manifest.html
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mouse-pr-remote
      url-base: https://github.com/ftc
    # - name: m165437
    #   url-base: https://github.com/M165437
  projects:
    - name: zmk
      remote: mouse-pr-remote
      revision: mouse-ftc
      import: app/west.yml
    # - name: nice-view-gem
    #   remote: m165437
    #   revision: main
  self:
    path: config
